// src/lib/components/header.svelte
<header
  class="flex w-full items-center justify-between py-6 px-4 md:px-6 bg-gray-900 flex-grow-0"
>
  <div class="container mx-auto flex flex-row justify-between items-baseline">
    <h1>
      <a href="/" class="text-xl font-bold">Rohan Nair</a>
    </h1>
    <nav class="flex items-center gap-4 md:gap-6">
      <a
        href="/posts"
        class="text-sm font-medium text-muted-foreground hover:text-primary transition-colors md:text-base"
        >Posts</a
      >
      <a
        href="/contact"
        class="text-sm font-medium text-muted-foreground hover:text-primary transition-colors md:text-base"
        >Contact</a
      >
    </nav>
  </div>
</header>

// app/components/global/Header.tsx
import { Link } from '@remix-run/react'

export function Header() {
  return (
    <div className="w-full">
      <div className="m-auto flex w-2/3 flex-row items-center pb-2 pt-10 text-lg">
        <Link to="/">
          <h2 className="m-0 p-0 text-2xl">Rohan Nair</h2>
        </Link>
        <nav className="ml-auto flex flex-row space-x-4"></nav>
      </div>
    </div>
  )
}
