// src/routes/posts/+page.svelte
<script lang="ts">
  import type { PageData } from "./$types";
  import Time from "svelte-time"

  export let data: PageData;
</script>

<h1 class="text-4xl mb-5">Posts</h1>
<ul class="grid gap-6 list-none p-0 m-0 w-full not-prose">
  {#each data.posts as { meta, path }}
    <li class="grid gap-2 p-0 m-0">
      <h2 class="mb-0">
        <a href={path} class="text-xl font-semibold no-underline">
          {meta.title}
        </a>
      </h2>
      <p class="text-gray-500">
        Posted <Time relative timestamp={meta.createdAt} format="dddd @ h:mm A · MMMM D, YYYY" />
      </p>
    </li>
  {/each}
</ul>

<div class="pagination">
  <!-- Add pagination controls here -->
</div>

// pages/posts/index.tsx
import Layout from '../../components/Layout'
import Head from 'next/head'
import Link from 'next/link'
import { getPosts } from '../../lib/posts'

export async function getStaticProps() {
  const posts = getPosts()
  return { props: { posts } }
}

interface PostProps {
  posts: { slug: string; meta: any }[]
}

export default function PostsPage({ posts }: PostProps) {
  return (
    <Layout>
      <Head>
        <title>Posts</title>
      </Head>
      <h1 className="text-4xl mb-5">Posts</h1>
      <ul className="grid gap-6 list-none p-0 m-0 w-full not-prose">
        {posts.map(({ slug, meta }) => (
          <li key={slug} className="grid gap-2 p-0 m-0">
            <h2 className="mb-0">
              <Link href={`/posts/${slug}`} className="text-xl font-semibold no-underline">
                {meta.title}
              </Link>
            </h2>
            <p className="text-gray-500">Posted {meta.createdAt}</p>
          </li>
        ))}
      </ul>
    </Layout>
  )
}
