// pages/posts/[slug].tsx
import Layout from '../../components/Layout'
import Head from 'next/head'
import { GetStaticPaths, GetStaticProps } from 'next'
import { getPosts, getPost } from '../../lib/posts'
import { mdToHtml } from '../../lib/markdown'

export const getStaticPaths: GetStaticPaths = async () => {
  const posts = getPosts()
  return {
    paths: posts.map((p) => ({ params: { slug: p.slug } })),
    fallback: false,
  }
}

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const slug = params?.slug as string
  const post = getPost(slug)
  const html = mdToHtml(post.content)
  return { props: { post: { ...post, html } } }
}

interface PostPageProps {
  post: ReturnType<typeof getPost> & { html: string }
}

export default function PostPage({ post }: PostPageProps) {
  return (
    <Layout>
      <Head>
        <title>{post.meta.title}</title>
        <meta name="description" content={post.meta.description} />
      </Head>
      <div className="space-y-4">
        <div>
          <h1 className="text-4xl font-bold">{post.meta.title}</h1>
          <p className="mt-0 text-sm text-gray-400">Published {post.meta.createdAt}</p>
        </div>
        <article className="article mt-8 max-w-4xl" dangerouslySetInnerHTML={{ __html: post.html }} />
      </div>
    </Layout>
  )
}

// src/routes/posts/[slug]/+page.svelte
<script lang="ts">
  import * as constants from "$lib/constants";

  export let data;
  const { post, metadata } = data;
</script>

<svelte:head>
  <title>{metadata.title} | {constants.title}</title>
  <meta name="description" content={metadata.description} />
</svelte:head>

<div class="flex flex-col w-full mt-8 mb-6">
  <h1 class="text-4xl text-left font-bold">{metadata.title}</h1>
  <p class="text-sm text-gray-300">Published: {metadata.date}</p>
</div>

<section class="flex w-full">
  <article class="prose">
    {@html post}
  </article>
</section>
